export default {
  'admin@devstack.co.kr': {
    'users': [
      {
         'is_wf':true,
         'wf':{
            'k8s_sa':'dl-admin'
         },
         'email':'tadmin@devstack.co.kr',
         'id':'77ff233162084cddb4a54cf58d5c1831',
         'name':'tadmin@devstack.co.kr',
         'domain_id':'default',
         'enabled':true,
         'default_project_id':'26461bbc0b7e4fd7bb10091a3db426ad',
         'password_expires_at':null,
         'options':{
            'lock_password':false
         }
      },
      {
         'is_wf':true,
         'wf':{
            'k8s_sa':'dl-modeler'
         },
         'email':'viewer@devstack.co.kr',
         'id':'c34ea56c49814ac98003bc98fee0923d',
         'name':'viewer@devstack.co.kr',
         'domain_id':'default',
         'enabled':true,
         'default_project_id':'26461bbc0b7e4fd7bb10091a3db426ad',
         'password_expires_at':null,
         'options':{
            'lock_password':false
         }
      },
      {
         'is_wf':true,
         'wf':{
            'k8s-sa':'dl-inferer'
         },
         'email':'executor@devstack.co.kr',
         'description':'dl-inferer',
         'id':'5f29308913f946d5a6b88b6a4c806f02',
         'name':'executor@devstack.co.kr',
         'domain_id':'default',
         'enabled':true,
         'default_project_id':'978a647141a04db2a28c19eba924f6c0',
         'password_expires_at':null,
         'options':{
            'lock_password':false
         }
      },
      {
         'email':'admin@devstack.co.kr',
         'description':'admin@devstack.co.kr',
         'id':'c69c8eef9fd54a56af5d7eb6acd7e138',
         'name':'admin@devstack.co.kr',
         'domain_id':'default',
         'enabled':true,
         'default_project_id':'70f6b4c1dc9040818ce0c8e35f33297c',
         'password_expires_at':null,
         'options':{
            'lock_password':false
         }
      }
   ]
  },
  'tadmin@devstack.co.kr': {
    'users':[
      {
         'is_wf':true,
         'wf':{
            'k8s_sa':'dl-admin'
         },
         'email':'tadmin@devstack.co.kr',
         'id':'77ff233162084cddb4a54cf58d5c1831',
         'name':'tadmin@devstack.co.kr',
         'domain_id':'default',
         'enabled':true,
         'default_project_id':'26461bbc0b7e4fd7bb10091a3db426ad',
         'password_expires_at':null,
         'options':{
            'lock_password':false
         }
      },
      {
         'is_wf':true,
         'wf':{
            'k8s_sa':'dl-modeler'
         },
         'email':'viewer@devstack.co.kr',
         'id':'c34ea56c49814ac98003bc98fee0923d',
         'name':'viewer@devstack.co.kr',
         'domain_id':'default',
         'enabled':true,
         'default_project_id':'26461bbc0b7e4fd7bb10091a3db426ad',
         'password_expires_at':null,
         'options':{
            'lock_password':false
         }
      },
      {
         'is_wf':true,
         'wf':{
            'k8s-sa':'dl-inferer'
         },
         'email':'executor@devstack.co.kr',
         'description':'dl-inferer',
         'id':'5f29308913f946d5a6b88b6a4c806f02',
         'name':'executor@devstack.co.kr',
         'domain_id':'default',
         'enabled':true,
         'default_project_id':'978a647141a04db2a28c19eba924f6c0',
         'password_expires_at':null,
         'options':{
            'lock_password':false
         }
      }
   ]
  }
}